\connect TesteLuizaLabs

CREATE TABLE public.Customers
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "Date" timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

ALTER TABLE public.Customers OWNER to postgres;

CREATE TABLE public.CustomerProducts
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "CustomerId" bigint NOT NULL,
    "Key" text COLLATE pg_catalog."default",
    "Date" timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    CONSTRAINT "PK_CustomerProducts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerProducts_Customers_CustomerId" FOREIGN KEY ("CustomerId")
        REFERENCES public.Customers ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);


ALTER TABLE public.CustomerProducts OWNER to postgres;

CREATE INDEX IF NOT EXISTS "IX_CustomerProducts_CustomerId"
    ON public.CustomerProducts USING btree
    ("CustomerId" ASC NULLS LAST)
    TABLESPACE pg_default;
